### ISSUE TITLE
استفاده از مارک‌داون؟

### ISSUE THREAD

**Issue by farooqkz** [amirbagh75/awesome-persian-blogs#10]
میگم چرا کارتون رو سخت کردید و از مارک‌داون استفاده نکردید؟

**Comment by ohmydevops** [comment]
چون با مارک‌داون نمیشه مطالب راست به چپ نوشت توی گیتهاب

**Comment by mskf1383** [comment]
<div dir="rtl">

کی گفته نمیشه؟ اینم راست به چپ:
</div>

```
<div dir="rtl">

text
</div>
```

**Comment by farooqkz** [comment]
همون که ایشون گفتن

مثلا:
<div dir="rtl">

 - یک آیتم
 - دگر آیتم
 - و آخرین آیتم

**Comment by mskf1383** [comment]
<div dir="rtl">

الان دارم به مارک دان ترجمه می کنم
منتظر پول ریکوئست باشید
</div>

**Comment by ohmydevops** [comment]
> کی گفته نمیشه؟ اینم راست به چپ:
> 
> ```
> <div dir="rtl">
> 
> text
> </div>
> ```

<div dir='rtl'>
خب منم همینطوری کردم که. مگه اینطوری نیست؟ منظورتون از مارک‌داون رو متوجه نشدم. توی گیتهاب من به جز گذاشتن dir=rtl روش دیگه‌ای برای راست به چپ کردن بلد نیستم. 
</div>

**Comment by ohmydevops** [comment]
آهان الان متوجه شدم. منظورتون برای لینک و لیست‌هاست.

**Comment by farooqkz** [comment]
بله :)

**Comment by ohmydevops** [comment]
ممنونم. این نکته رو نمیدونستم. خیلی بهتر و ترتمیزتر شد.
متشکرم @farooqkz @mskf1383
