### ISSUE TITLE
سرباز اسنیک 

### ISSUE THREAD

**Issue by Solidsnake13** [amirbagh75/awesome-persian-blogs#20]
نه نویسندم، نه بلدم درست بنویسم. هرچی ام می نویسم دروغه. 

https://virgool.io/@solidsnake

**Comment by ohmydevops** [comment]
سلام  بر شما.
هویت نویسنده پشت وبلاگ شما چه فردیه؟ یکی از پارامترهایی که من برای لیست این وبلاگ‌ها داشتم این بوده که یک هویت پشتش باشه. مثلا مشخص باشه کی مینویسه یا چه شرکتی مینویسه

**Comment by Solidsnake13** [comment]
سلام، شبتون بخیر.
ایده‌ی پشت این وبلاگ ناشناس بودنه، اگر فکر می کنید نمی تونید بذارید توی
لیستتون مشکلی نیست :) کاملا قابل درک هست :) مرسی از پیگیریتون، اما دوست
ندارم با هویت واقعیم شناخته بشم.

یک دنیا ممنون از شما
