### ISSUE TITLE
پیدا کردن راه‌حلی برای دسته‌بندی وبلاگ‌ها

### ISSUE THREAD

**Issue by ohmydevops** [amirbagh75/awesome-persian-blogs#3]
<div dir='rtl'>
الان کلی وبلاگ به صورت لیستی داره ذخیره میشه. برای شروع خوبه ولی برای ادامه چی؟ فکر نمیکنم جالب باشه. فضای همه وبلاگ‌ها متفاوته باهم و ممکنه مخاطبان هر حوزه‌ای رو دچار سردرگمی کنه که آدم‌های حوزه خودشونو پیدا کنن و دنبال کنن. راه‌حل چیه خب؟ نمیدونم. اینجا قراره فکرامو بنویسم ببینم چه میشه کرد.
</div>

**Comment by ohmydevops** [comment]
دسته بندی بر اساس محتوایی که مینویسن؟ مثلا یکی روزمره نویسی میکنه.یکی تکنولوژی. یکی ترکیبی از چند چیز و ....

**Comment by ohmydevops** [comment]
بعضی وبلاگ ها از هر موضوعی مینویسن. این‌ها رو چطور میخوای توی دسته بندی قرار بدی؟ دسته بندی عمومی مثلا؟ متفرقه؟

**Comment by geeksesi** [comment]
> بعضی وبلاگ ها از هر موضوعی مینویسن. این‌ها رو چطور میخوای توی دسته بندی قرار بدی؟ دسته بندی عمومی مثلا؟ متفرقه؟

بر اساس موضوع اصلی وبلاگشون.
مثلا یکی موضوع اصلیش تکنولوژیه اما این وسط بعضی اوقات روزمره نویسی هم می کنه...
؟

**Comment by ohmydevops** [comment]
> > بعضی وبلاگ ها از هر موضوعی مینویسن. این‌ها رو چطور میخوای توی دسته بندی قرار بدی؟ دسته بندی عمومی مثلا؟ متفرقه؟
> 
> بر اساس موضوع اصلی وبلاگشون.
> مثلا یکی موضوع اصلیش تکنولوژیه اما این وسط بعضی اوقات روزمره نویسی هم می کنه...
> ؟

<div dir='rtl'>
فکر خوبیه. در حقیقت موضوع اصلی وبلاگ رو میشه بولد کرد و الباقی موضوعاتش رو نادید گرفت. برای مثال این دوتا وبلاگ رو چطوری دسته بندی میکنی؟
</div>

https://jadi.net/
http://saraderhami.com/

**Comment by farooqkz** [comment]
وبلاگ قدیمی جادی رو واقعه ایده‌ای ندارم کجا بزاریش...

**Comment by geeksesi** [comment]
> فکر خوبیه. در حقیقت موضوع اصلی وبلاگ رو میشه بولد کرد و الباقی موضوعاتش رو نادید گرفت. برای مثال این دوتا وبلاگ رو چطوری دسته بندی میکنی؟
> 
> https://jadi.net/
> http://saraderhami.com/

سخت شد واقعا.
می تونیم از خود وبلاگ نویس بخواهیم بیاد ۳ تا موضوع اصلی از وبلاگش رو بگه.

یا منه مخاطب مثلا جادی رو یبشتر موضوع تکنولوژیش رو بولد می دونم

**Comment by ohmydevops** [comment]
> > فکر خوبیه. در حقیقت موضوع اصلی وبلاگ رو میشه بولد کرد و الباقی موضوعاتش رو نادید گرفت. برای مثال این دوتا وبلاگ رو چطوری دسته بندی میکنی؟
> > https://jadi.net/
> > http://saraderhami.com/
> 
> سخت شد واقعا.
> می تونیم از خود وبلاگ نویس بخواهیم بیاد ۳ تا موضوع اصلی از وبلاگش رو بگه.
> 
> یا منه مخاطب مثلا جادی رو یبشتر موضوع تکنولوژیش رو بولد می دونم

<div dir='rtl'>
خب نمیخوایم قضیه اینقدر سخت و زمان‌بر بشه. فعلا که تعداد وبلاگ‌ها زیاد نیست بدون دسته بندی میشه پیش رفت ولی خب باید یک روش معقول ولی ساده پیدا کنیم. یک چیزی که به ذهنم رسید این بود که میتونیم برای هر وبلاگ یک توضیح کوچیک بزاریم. و دسته‌بندی الفبایی کنیم. مثلا اینطوری:

وبلاگ جادی - جادی بیشتر درباره x و y و z مینویسه .
سارا درهمی - سارا بیشتر درباره موضوعات اجتماعی و ... مینویسه.

اینطوری از پیچیدگی دسته‌بندی تحت یک عنوان خلاص میشیم. و با دسته‌بندی الفبایی هم میشه یک نظم برای نوشتنش پیدا کرد.
</div>

**Comment by farooqkz** [comment]
<div dir="rtl">
آره میتونیم دسته‌بندی کنیم به روش سنتی اما یک وبلاگ در بیش از یک دسته قرار بگیره مثلا در مورد وبلاگ جادی میوفته توی دسته X و Y و Z

**Comment by alimirjamali** [comment]
پیشنهاد بنده بر این است که تا گرفتن تصمیم مناسب برای دسته بندی وبلاگ‌ها، بر اساس نام دامنه سورت گردند تا پیدا کردن آنها در لیست راحت‌تر باشد.

**Comment by amirbagh75** [comment]
<div dir='rtl'>

ممنون از دوستان
من این مدت سفر بودم و فرصت نکردم کارها رو بررسی کنم. توی این هفته سعی میکنم این مورد رو یک تصمیمی به کمک پیشنهادات موجود براش بگیریم تا ببینیم چی میشه

</div>

**Comment by ohmydevops** [comment]
نمیدونم چرا هرچی فکر میکنم هیچ راه معقولی برای دسته بندی به ذهنم نمیرسه! چرا همچین کار به ظاهر ساده‌ای باید اینقدر پیچیده بشه. ای بابا. شاید هم دارم اشتباه میزنم و اصلا دسته‌بندی چیزی که دسته‌بندی نداره کلا تصمیم نادرستیه

**Comment by ohmydevops** [comment]
> پیشنهاد بنده بر این است که تا گرفتن تصمیم مناسب برای دسته بندی وبلاگ‌ها، بر اساس نام دامنه سورت گردند تا پیدا کردن آنها در لیست راحت‌تر باشد.

@alimirjamali 

<div dir='rtl'>
پشنهاد شما معقول‌ترین راهکاره به نظرم. در اولین فرصت انجامش میدم و توی فایل contribute هم میگم که اگر کسی خواست PR بزنه ترتیب الفبایی رو حفظ کنه
</div>

**Comment by ohmydevops** [comment]
![image](https://user-images.githubusercontent.com/21690865/117728980-6be6d980-b1ff-11eb-93cc-cef518c8a907.png)

<div dir='rtl'>

به وسیله این سایت مرتب کردم: [https://onlinestringtools.com/sort-strings](https://onlinestringtools.com/sort-strings)

</div>

**Comment by ohmydevops** [comment]
ممنون از نظرات ارزشمندتون دوستان. به نظرم همین مرتب‌سازی کافیه
