### ISSUE TITLE
اضافه کردن کرم‌های کامپیوتر

### ISSUE THREAD

**Issue by farooqkz** [amirbagh75/awesome-persian-blogs#6]
اگر میخواید تا پول رکوئست بدم و اضافه کنمش. وبلاگ خودم و یکی از دوستان.
https://pcworms.blog.ir

**Comment by farooqkz** [comment]
اگر موافق اضافه کردنش نیستید ایشو رو ببندید و اگر هم بله یا اضافه کنید یا بگید خودم پول رکوئست بزنم.
:)

**Comment by ohmydevops** [comment]
سلام سلام
یک pr بدید.
